--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/7TogkKeyShop
build-by-default: true
branches:
- main
projects:
  7TogkKeyShop:
    path: ""
  libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.0
...
