name: 7TogkKeyShop
main: angga7togk\keyshop\KeyShop
version: 3.0.0
api:
- 4.0.0
- 5.0.0
author: Angga7Togk
description: "Open 7TogkKeyShop By Angga7Togk"

commands:
  keyshop:
    description: "Open The KeyShop"
    permission: keyshop.cmd

permissions:
  keyshop.cmd:
    default: true
