### [ 7TogkKeyShop ] ###

# use § To Change Colors Text

# Need plugin EconomyAPI and PiggyCrate to launch this plugin

Title: "Eternity - KeyShops"
1:
  Key:
    Name: "Knight" # Key Name
    Price: 1000000 # Price key
  Button:
    Name: "§l§eKnight Key" # Button Name
  Message:
    Succes: "§aSucces buy a key §eKnight" # Success Message Buy A Key
    Failed: "§cYour money is not enough" # Failed Message Buy A Key
2:
  Key:
    Name: "Corrosion" # Key Name
    Price: 2000000 # Price key
  Button:
    Name: "§l§eCorrosion Key" # Button Name
  Message:
    Succes: "§aSucces buy a key §eCorrosion" # Success Message Buy A Key
    Failed: "§cYour money is not enough"
3:
  Key:
    Name: "" # Key Name
    Price: 1000000 # Price key
  Button:
    Name: "§l§e Key" # Button Name
  Message:
    Succes: "§aSucces buy a key §eVeteran" # Success Message Buy A Key
    Failed: "§cYour money is not enough"
